FROM ubuntu

# Set our env variable
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-opencv
RUN apt-get clean

RUN pip3 install opencv-python
RUN pip3 install paho-mqtt


WORKDIR /
COPY image_saver.py .

CMD python3 image_saver.py $SAVE_FOLDER
